{
  "name": "c10b5156-7161-426e-b017-a01323dbb33f",
  "compatibilityLevel": 1606,
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Avaliacoes_Maturidade",
        "lineageTag": "60474d17-5260-4786-8087-a7010ea63e45",
        "columns": [
          {
            "name": "AvaliacaoID",
            "dataType": "int64",
            "sourceColumn": "AvaliacaoID",
            "formatString": "0",
            "lineageTag": "e71cdf85-7afc-4bbc-9c31-747fadea793a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Start time",
            "dataType": "dateTime",
            "sourceColumn": "Start time",
            "formatString": "General Date",
            "lineageTag": "6ab22156-5c5e-4b0f-99c9-240d10479364",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "relationship": "2a1a7c0f-a3a7-4b65-9bc1-5a550b779b2e",
                "defaultHierarchy": {
                  "table": "LocalDateTable_a80ef2b5-2c9d-4b93-b7fb-2e3338a89f21",
                  "hierarchy": "Hierarquia de datas"
                },
                "isDefault": true
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          },
          {
            "name": "DataAvaliacao",
            "dataType": "dateTime",
            "sourceColumn": "DataAvaliacao",
            "formatString": "yyyy-MM-dd HH:mm",
            "lineageTag": "090d02cb-fad2-4458-a0c6-3493ef057413",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "relationship": "4a6ad4e6-7de2-4062-8e0c-e498ae250ddc",
                "defaultHierarchy": {
                  "table": "LocalDateTable_6dd670b3-9c41-40c2-9037-f42df2a40ccc",
                  "hierarchy": "Hierarquia de datas"
                },
                "isDefault": true
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "EmailRespondente",
            "dataType": "string",
            "sourceColumn": "EmailRespondente",
            "lineageTag": "214db333-a4db-4e01-a5b6-2551dedc3915",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          },
          {
            "name": "Respondente",
            "dataType": "string",
            "sourceColumn": "Respondente",
            "lineageTag": "f4e61eca-f1ac-4feb-843d-2dc6de3741aa",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          },
          {
            "name": "Cliente",
            "dataType": "string",
            "sourceColumn": "Cliente",
            "lineageTag": "04072518-1d46-4655-b034-c81c0e0caef7",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "AreaNegocio",
            "dataType": "string",
            "sourceColumn": "AreaNegocio",
            "lineageTag": "3e3751f1-8067-4b32-878c-9657bd8cf8fc",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "1_Total",
            "dataType": "double",
            "sourceColumn": "1_Total",
            "lineageTag": "cfec5510-a888-4a6c-a6f6-952d36524cdf",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "2_Total",
            "dataType": "double",
            "sourceColumn": "2_Total",
            "lineageTag": "4bc9c555-13b0-47b8-9c1f-210cfd86ad26",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "3_Total",
            "dataType": "double",
            "sourceColumn": "3_Total",
            "lineageTag": "28744d66-16aa-41a7-9168-d31a0c761c2f",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "4_Total",
            "dataType": "double",
            "sourceColumn": "4_Total",
            "lineageTag": "36b39447-fa46-45ec-b0ba-d6c11985a3e1",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "5_Total",
            "dataType": "double",
            "sourceColumn": "5_Total",
            "lineageTag": "64ef7780-488f-41b3-b11c-9a6d94a3bdcb",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "6_Total",
            "dataType": "double",
            "sourceColumn": "6_Total",
            "lineageTag": "0e4d5bca-1669-4ed4-8854-660cb2f4dd6b",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "7_Total",
            "dataType": "double",
            "sourceColumn": "7_Total",
            "lineageTag": "c88c628d-e12f-4241-9f38-62074c225f4a",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "8_Total",
            "dataType": "double",
            "sourceColumn": "8_Total",
            "lineageTag": "62b80886-87d5-4933-8404-7c83f1b6f825",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "ScoreGeneral",
            "dataType": "double",
            "sourceColumn": "ScoreGeneral",
            "lineageTag": "bf5f1d4c-7d05-42f2-800a-d722e5eafc82",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "formatString": "0.00"
          },
          {
            "name": "ScoreMaximo",
            "dataType": "int64",
            "sourceColumn": "ScoreMaximo",
            "formatString": "0",
            "lineageTag": "c769b2ec-6752-49a1-b1c1-5bc834595e00",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "DataAvaliacaoDia",
            "dataType": "dateTime",
            "sourceColumn": "DataAvaliacaoDia",
            "formatString": "yyyy-MM-dd",
            "lineageTag": "3a9e9e02-6133-452a-a608-3f2677a86f57",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "relationship": "5853bb78-40a9-43b2-9537-30aa47b256ed",
                "defaultHierarchy": {
                  "table": "LocalDateTable_fac499e5-2eb6-445e-9e22-3f649110ac51",
                  "hierarchy": "Hierarquia de datas"
                },
                "isDefault": true
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ClienteArea",
            "dataType": "string",
            "sourceColumn": "ClienteArea",
            "lineageTag": "36f88dee-e400-4edd-ac1e-f6d9a674fed6",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "StatusAvaliacao",
            "dataType": "string",
            "sourceColumn": "StatusAvaliacao",
            "lineageTag": "dcf31a7e-9f56-4517-a1e1-f4ff67a264a6",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Status Exibição",
            "dataType": "string",
            "expression": "IF(Avaliacoes_Maturidade[StatusAvaliacao] = \"Validated\", \"Valid\", \"Incomplete\")",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "Avaliacoes_Maturidade",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    // Fictional baseline SYN-MAT-BASE-001; no external data source.",
                "    Source = #table({\"AvaliacaoID\", \"Start time\", \"DataAvaliacao\", \"EmailRespondente\", \"Respondente\", \"Cliente\", \"AreaNegocio\", \"1_Total\", \"2_Total\", \"3_Total\", \"4_Total\", \"5_Total\", \"6_Total\", \"7_Total\", \"8_Total\", \"ScoreGeneral\", \"ScoreMaximo\", \"DataAvaliacaoDia\", \"ClienteArea\", \"StatusAvaliacao\"}, {{1, #datetime(2026,9,1,9,0,0), #datetime(2026,9,1,10,0,0), null, \"Synthetic assessor\", \"Synthetic Organization\", \"Unit A\", 2, 1.5, 2, 1, 2.5, 1, 2.25, 1.75, 1.75, 3, #datetime(2026,9,1,0,0,0), \"Synthetic Organization | Unit A\", \"Validated\"}}),",
                "    Typed = Table.TransformColumnTypes(Source, {{\"AvaliacaoID\", Int64.Type}, {\"Start time\", type datetime}, {\"DataAvaliacao\", type datetime}, {\"EmailRespondente\", type text}, {\"Respondente\", type text}, {\"Cliente\", type text}, {\"AreaNegocio\", type text}, {\"1_Total\", type number}, {\"2_Total\", type number}, {\"3_Total\", type number}, {\"4_Total\", type number}, {\"5_Total\", type number}, {\"6_Total\", type number}, {\"7_Total\", type number}, {\"8_Total\", type number}, {\"ScoreGeneral\", type number}, {\"ScoreMaximo\", Int64.Type}, {\"DataAvaliacaoDia\", type datetime}, {\"ClienteArea\", type text}, {\"StatusAvaliacao\", type text}}),",
                "    SemStatus = Table.RemoveColumns(Typed, {\"StatusAvaliacao\"}),",
                "    Validacao = Table.AddColumn(SemStatus, \"StatusAvaliacao\", each let\n        Scores = {[1_Total], [2_Total], [3_Total], [4_Total], [5_Total], [6_Total], [7_Total], [8_Total]},\n        NumerosValidos = List.NonNullCount(Scores) = 8 and List.AllTrue(List.Transform(Scores, each if _ = null then false else _ >= 0 and _ <= 3)),\n        IdentificacaoValida = [Cliente] <> null and Text.Trim([Cliente]) <> \"\" and [AreaNegocio] <> null and Text.Trim([AreaNegocio]) <> \"\" and [AvaliacaoID] <> null and [DataAvaliacao] <> null,\n        GeralValido = if [ScoreGeneral] = null or not NumerosValidos then false else [ScoreGeneral] >= 0 and [ScoreGeneral] <= 3 and Number.Abs([ScoreGeneral] - List.Average(Scores)) < 0.000001\n        in if IdentificacaoValida and NumerosValidos and GeralValido then \"Validated\" else \"Incomplete\", type text)",
                "in",
                "    Validacao"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "DateTableTemplate_b615e920-2afe-4fe2-8d5e-fa05f0d6fda1",
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "91468632-caed-4736-9ec2-a11336214c8f",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "formatString": "General Date",
            "lineageTag": "00001e51-b388-40c4-8498-da789888d3bf",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Ano",
            "dataType": "int64",
            "isHidden": true,
            "expression": "YEAR([Date])",
            "formatString": "0",
            "lineageTag": "ea92a088-2b0b-4372-b07b-e13b817464cb",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "MONTH([Date])",
            "formatString": "0",
            "lineageTag": "ac3c24b2-40cc-4be2-ab0d-cd21b179527a",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Mês",
            "dataType": "string",
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "e44e04db-2fa8-41fa-96b6-224450f39325",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "lineageTag": "b7cebc94-9824-46e6-a9f9-c6545eed87c2",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Trimestre",
            "dataType": "string",
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "ea7c95d7-9e5d-4394-a7d4-5f670cf6826a",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Dia",
            "dataType": "int64",
            "isHidden": true,
            "expression": "DAY([Date])",
            "formatString": "0",
            "lineageTag": "df981331-a2b0-49ed-8085-01c11331fcb3",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DateTableTemplate_b615e920-2afe-4fe2-8d5e-fa05f0d6fda1",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "lineageTag": "6a699fba-140a-463e-9714-f01c6c22837c",
            "levels": [
              {
                "name": "Ano",
                "ordinal": 0,
                "column": "Ano",
                "lineageTag": "7537d723-d8bf-4842-9e51-2e78ba23d705"
              },
              {
                "name": "Trimestre",
                "ordinal": 1,
                "column": "Trimestre",
                "lineageTag": "20f436f1-c531-4a10-808a-84e89b5e2871"
              },
              {
                "name": "Mês",
                "ordinal": 2,
                "column": "Mês",
                "lineageTag": "5029b56b-d12b-4285-bc92-9c1a566e8d1b"
              },
              {
                "name": "Dia",
                "ordinal": 3,
                "column": "Dia",
                "lineageTag": "eefcfbad-fe69-470b-bcec-23605f48bdd3"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ]
      },
      {
        "name": "LocalDateTable_a80ef2b5-2c9d-4b93-b7fb-2e3338a89f21",
        "isHidden": true,
        "showAsVariationsOnly": true,
        "lineageTag": "2834da22-2972-457d-bcfd-7f5523bdc424",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "formatString": "General Date",
            "lineageTag": "7f139a24-c397-4282-ba7f-62969aa3afbb",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Ano",
            "dataType": "int64",
            "isHidden": true,
            "expression": "YEAR([Date])",
            "formatString": "0",
            "lineageTag": "fce62931-3bc8-4608-9389-53545d04a355",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "MONTH([Date])",
            "formatString": "0",
            "lineageTag": "a175f1db-cd16-4b86-9922-6924d76f1cdd",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Mês",
            "dataType": "string",
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "43a2525b-7a9a-4581-b600-e0d148f575a7",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "lineageTag": "dfebb934-8ae9-402c-9b0b-5be7db843bd9",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Trimestre",
            "dataType": "string",
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "3851bcbd-52fc-42ed-bf5e-71cda02a45b5",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Dia",
            "dataType": "int64",
            "isHidden": true,
            "expression": "DAY([Date])",
            "formatString": "0",
            "lineageTag": "14622528-2dad-4770-ba1d-a92d1f305988",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "LocalDateTable_a80ef2b5-2c9d-4b93-b7fb-2e3338a89f21",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(Year(MIN('Avaliacoes_Maturidade'[Start time])), 1, 1), Date(Year(MAX('Avaliacoes_Maturidade'[Start time])), 12, 31))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "lineageTag": "935bc82c-1aa9-4bd7-887c-2fb4cff0a1d7",
            "levels": [
              {
                "name": "Ano",
                "ordinal": 0,
                "column": "Ano",
                "lineageTag": "0b0939fa-763e-4c7e-92dc-78d2f1ffcd51"
              },
              {
                "name": "Trimestre",
                "ordinal": 1,
                "column": "Trimestre",
                "lineageTag": "72ed81e3-02f6-48b6-9674-d44e473de197"
              },
              {
                "name": "Mês",
                "ordinal": 2,
                "column": "Mês",
                "lineageTag": "8a8b372f-e2e5-4279-a7ea-d1a0c0754d75"
              },
              {
                "name": "Dia",
                "ordinal": 3,
                "column": "Dia",
                "lineageTag": "7e8401a5-3895-4362-a9f0-df852b006ac4"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ]
      },
      {
        "name": "LocalDateTable_6dd670b3-9c41-40c2-9037-f42df2a40ccc",
        "isHidden": true,
        "showAsVariationsOnly": true,
        "lineageTag": "ae593de1-a422-4668-8b13-e15ae1cef0df",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "formatString": "General Date",
            "lineageTag": "ee0cd0ba-00d2-45ef-ad5c-e6435984fa8c",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Ano",
            "dataType": "int64",
            "isHidden": true,
            "expression": "YEAR([Date])",
            "formatString": "0",
            "lineageTag": "e2bc739d-8d1e-4e52-bdf9-9264b2b0b897",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "MONTH([Date])",
            "formatString": "0",
            "lineageTag": "2f96cd47-ada0-4e72-a5e4-7053760cfeb8",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Mês",
            "dataType": "string",
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "c7ddd244-6524-4476-b6d1-371fecbae72d",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "lineageTag": "aba2a304-2153-4988-95d3-66a9abb38898",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Trimestre",
            "dataType": "string",
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "304d1eae-e072-462b-a378-354dac4f9f84",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Dia",
            "dataType": "int64",
            "isHidden": true,
            "expression": "DAY([Date])",
            "formatString": "0",
            "lineageTag": "12f34136-19e2-4578-b877-8b19dd22c4e7",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "LocalDateTable_6dd670b3-9c41-40c2-9037-f42df2a40ccc",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(Year(MIN('Avaliacoes_Maturidade'[DataAvaliacao])), 1, 1), Date(Year(MAX('Avaliacoes_Maturidade'[DataAvaliacao])), 12, 31))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "lineageTag": "d2f97ad7-b2f7-4f72-8e09-604d2865e2e4",
            "levels": [
              {
                "name": "Ano",
                "ordinal": 0,
                "column": "Ano",
                "lineageTag": "1e8b2a1e-c492-4298-8812-707376a014c4"
              },
              {
                "name": "Trimestre",
                "ordinal": 1,
                "column": "Trimestre",
                "lineageTag": "9868edad-2303-4ca1-900c-df170282b9e0"
              },
              {
                "name": "Mês",
                "ordinal": 2,
                "column": "Mês",
                "lineageTag": "5e3e89db-f949-4bc4-b5df-6ef63725d3ff"
              },
              {
                "name": "Dia",
                "ordinal": 3,
                "column": "Dia",
                "lineageTag": "ab051196-a4b6-46e0-b09b-800fc788bc6e"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ]
      },
      {
        "name": "LocalDateTable_fac499e5-2eb6-445e-9e22-3f649110ac51",
        "isHidden": true,
        "showAsVariationsOnly": true,
        "lineageTag": "9cf59169-a281-41ee-983e-59c49a85ffa3",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "formatString": "General Date",
            "lineageTag": "94d5d875-99a1-441e-ad83-0b7fa5c9b8f8",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Ano",
            "dataType": "int64",
            "isHidden": true,
            "expression": "YEAR([Date])",
            "formatString": "0",
            "lineageTag": "91a381ca-e305-4a15-b1da-8d53617ce59f",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "MONTH([Date])",
            "formatString": "0",
            "lineageTag": "c80de99b-07bf-4138-a780-c663bc7bdb77",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Mês",
            "dataType": "string",
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "59b9f4a5-ee68-4043-bf0b-ddb642efd498",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "lineageTag": "b43f1b1e-d301-40c1-8f71-5ae5d98d0a90",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Trimestre",
            "dataType": "string",
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "dbfe5763-4885-49cb-826b-34072f8e48a4",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Dia",
            "dataType": "int64",
            "isHidden": true,
            "expression": "DAY([Date])",
            "formatString": "0",
            "lineageTag": "919b0081-1083-4637-a7d5-890c4c0b68e7",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "LocalDateTable_fac499e5-2eb6-445e-9e22-3f649110ac51",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(Year(MIN('Avaliacoes_Maturidade'[DataAvaliacaoDia])), 1, 1), Date(Year(MAX('Avaliacoes_Maturidade'[DataAvaliacaoDia])), 12, 31))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "lineageTag": "e5d0db34-289e-4765-95c3-b44f6ebdb24c",
            "levels": [
              {
                "name": "Ano",
                "ordinal": 0,
                "column": "Ano",
                "lineageTag": "c0af079e-09c3-43d0-99d8-d7f5e3a02c4a"
              },
              {
                "name": "Trimestre",
                "ordinal": 1,
                "column": "Trimestre",
                "lineageTag": "d38b455f-3f76-45be-bd83-5472dfb0817f"
              },
              {
                "name": "Mês",
                "ordinal": 2,
                "column": "Mês",
                "lineageTag": "9acff400-0381-46b5-abb7-53c6086fab72"
              },
              {
                "name": "Dia",
                "ordinal": 3,
                "column": "Dia",
                "lineageTag": "bb2835a9-840d-4f3b-a30c-ba1b0de6e6aa"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ]
      },
      {
        "name": "_Medidas",
        "lineageTag": "12c9ee4a-512c-4956-83fb-c3e68dbe953c",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Controle",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Controle]",
            "formatString": "0",
            "lineageTag": "5ab7845a-2ac8-4bfa-a73c-59cffb5cd405",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "_Medidas",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "ROW(\"Controle\", 1)"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Total Avaliações Validateds",
            "expression": "[Total Avaliações Válidas]",
            "lineageTag": "70f33069-0339-41a3-b5f9-f4e37db1561f",
            "displayFolder": "00 Controle",
            "formatString": "0",
            "isHidden": true
          },
          {
            "name": "Score Geral Médio",
            "expression": [
              "",
              "CALCULATE(",
              "    AVERAGE(Avaliacoes_Maturidade[ScoreGeneral]),",
              "    Avaliacoes_Maturidade[StatusAvaliacao] = \"Validated\"",
              ")"
            ],
            "formatString": "0.00",
            "lineageTag": "4041f6b8-9b41-49b2-b6d7-ff4428cab5d6",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "03 Histórico"
          },
          {
            "name": "Score Máximo",
            "expression": "3",
            "formatString": "0.00",
            "lineageTag": "dabeb1fa-d0d3-4f9a-8fba-451b139a925b",
            "displayFolder": "01 Visão executiva"
          },
          {
            "name": "% Maturidade",
            "expression": "DIVIDE([Score Última Avaliação], [Score Máximo])",
            "formatString": "0.0%",
            "lineageTag": "6b79c1ae-d678-4639-b9f4-fd13a8aae5ef",
            "displayFolder": "01 Visão executiva"
          },
          {
            "name": "Score Médio por Pilar",
            "expression": [
              "",
              "CALCULATE(",
              "    AVERAGE(Score_Por_Pilar[ScorePilar]),",
              "    Score_Por_Pilar[StatusAvaliacao] = \"Validated\"",
              ")"
            ],
            "lineageTag": "ff6b6df3-0206-4612-8921-fcc3ed86a0b9",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "03 Histórico",
            "formatString": "0.00"
          },
          {
            "name": "Nível de Maturidade",
            "expression": "VAR S = [Score Última Avaliação]\nRETURN SWITCH(TRUE(), ISBLANK(S), \"No assessment\", S < 0 || S > 3, \"Invalid score\", S < 0.75, \"Initial\", S < 1.50, \"Developing\", S < 2.25, \"Defined\", S < 2.75, \"Managed\", \"Optimized\")",
            "lineageTag": "0feda92a-180e-4daf-a390-bf5896dac846",
            "displayFolder": "01 Visão executiva"
          },
          {
            "name": "Data Última Avaliação",
            "expression": "VAR IdAtual = [ID Última Avaliação]\nRETURN IF(NOT ISBLANK(IdAtual), CALCULATE(MAX(Avaliacoes_Maturidade[DataAvaliacao]), Avaliacoes_Maturidade[AvaliacaoID] = IdAtual))",
            "formatString": "yyyy-MM-dd HH:mm",
            "lineageTag": "dc7d49a7-eee8-49fd-b07c-217551877fb2",
            "displayFolder": "01 Visão executiva"
          },
          {
            "name": "Score Última Avaliação",
            "expression": "VAR IdAtual = [ID Última Avaliação]\nRETURN IF(NOT ISBLANK(IdAtual), CALCULATE(MAX(Avaliacoes_Maturidade[ScoreGeneral]), Avaliacoes_Maturidade[AvaliacaoID] = IdAtual))",
            "formatString": "0.00",
            "lineageTag": "8c9e0efc-d842-484a-a45f-9ed49661f2a3",
            "displayFolder": "01 Visão executiva"
          },
          {
            "name": "Título Cliente Selecionado",
            "expression": "SELECTEDVALUE(Avaliacoes_Maturidade[ClienteArea], \"Select an organization and unit\")",
            "lineageTag": "e6768a18-63a6-4be2-b48d-470792e1ddc2",
            "displayFolder": "01 Visão executiva"
          },
          {
            "name": "Score Radar",
            "expression": [
              "",
              "CALCULATE(",
              "    AVERAGE(Score_Por_Pilar[ScorePilar]),",
              "    Score_Por_Pilar[StatusAvaliacao] = \"Validated\"",
              ")"
            ],
            "lineageTag": "d198fcb8-5918-4847-9659-4001218b2f60",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "03 Histórico",
            "formatString": "0.00"
          },
          {
            "name": "Score Máximo Radar",
            "expression": "IF(NOT ISBLANK([ID Última Avaliação]), 3)",
            "formatString": "0.00",
            "lineageTag": "c16800c3-18bd-46da-a858-4b2a333dd7eb",
            "displayFolder": "02 Pilares"
          },
          {
            "name": "Score Radar Última Avaliação",
            "expression": "VAR IdAtual = [ID Última Avaliação]\nRETURN IF(NOT ISBLANK(IdAtual), CALCULATE(MAX(Score_Por_Pilar[ScorePilar]), Avaliacoes_Maturidade[AvaliacaoID] = IdAtual))",
            "formatString": "0.00",
            "lineageTag": "4a34f656-38b2-44f9-b742-73e73d9746d3",
            "displayFolder": "02 Pilares"
          },
          {
            "name": "ID Última Avaliação",
            "lineageTag": "bfac0c99-be71-417c-8e60-fdd8ce91e3d9",
            "expression": "VAR Linhas = FILTER(Avaliacoes_Maturidade, Avaliacoes_Maturidade[StatusAvaliacao] = \"Validated\")\nRETURN IF(HASONEVALUE(Avaliacoes_Maturidade[ClienteArea]),\n    MAXX(TOPN(1, Linhas, Avaliacoes_Maturidade[DataAvaliacao], DESC, Avaliacoes_Maturidade[AvaliacaoID], DESC), Avaliacoes_Maturidade[AvaliacaoID]))",
            "displayFolder": "00 Controle",
            "formatString": "0",
            "isHidden": true
          },
          {
            "name": "Score Atual Exibição",
            "lineageTag": "c35d0182-9620-4ee9-8af3-68986a179420",
            "expression": "IF(ISBLANK([Score Última Avaliação]), \"—\", FORMAT([Score Última Avaliação], \"0.00\", \"en-US\") & \" / 3.00\")",
            "displayFolder": "01 Visão executiva"
          },
          {
            "name": "ID Avaliação Anterior",
            "lineageTag": "863a64c5-e82f-47fb-8b1c-618cf6edf40f",
            "expression": "VAR IdAtual = [ID Última Avaliação]\nVAR Linhas = FILTER(Avaliacoes_Maturidade, Avaliacoes_Maturidade[StatusAvaliacao] = \"Validated\" && Avaliacoes_Maturidade[AvaliacaoID] <> IdAtual)\nRETURN IF(NOT ISBLANK(IdAtual), MAXX(TOPN(1, Linhas, Avaliacoes_Maturidade[DataAvaliacao], DESC, Avaliacoes_Maturidade[AvaliacaoID], DESC), Avaliacoes_Maturidade[AvaliacaoID]))",
            "displayFolder": "00 Controle",
            "formatString": "0",
            "isHidden": true
          },
          {
            "name": "Score Avaliação Anterior",
            "lineageTag": "e5751fe3-87a2-4202-841c-c87c5056cf30",
            "expression": "VAR IdAnterior = [ID Avaliação Anterior]\nRETURN IF(NOT ISBLANK(IdAnterior), CALCULATE(MAX(Avaliacoes_Maturidade[ScoreGeneral]), Avaliacoes_Maturidade[AvaliacaoID] = IdAnterior))",
            "displayFolder": "03 Histórico",
            "formatString": "0.00"
          },
          {
            "name": "Variação em Pontos",
            "lineageTag": "bad678f8-0f32-4a3a-99d7-f78d82cad26c",
            "expression": "IF(NOT ISBLANK([Score Avaliação Anterior]), [Score Última Avaliação] - [Score Avaliação Anterior])",
            "displayFolder": "03 Histórico",
            "formatString": "+0.00;-0.00;0.00"
          },
          {
            "name": "Variação Exibição",
            "lineageTag": "2dd899a8-131f-4617-9703-dc80c3b0fd95",
            "expression": "IF(ISBLANK([Variação em Pontos]), \"No previous\", FORMAT([Variação em Pontos], \"+0.00;-0.00;0.00\", \"en-US\") & \" point(s)\")",
            "displayFolder": "01 Visão executiva"
          },
          {
            "name": "Total Avaliações Válidas",
            "lineageTag": "7bbebe1a-bd44-496f-b801-0a174ce0caed",
            "expression": "COALESCE(CALCULATE(DISTINCTCOUNT(Avaliacoes_Maturidade[AvaliacaoID]), Avaliacoes_Maturidade[StatusAvaliacao] = \"Validated\"), 0)",
            "displayFolder": "04 Qualidade",
            "formatString": "0"
          },
          {
            "name": "Avaliações Incompletas",
            "lineageTag": "5614634b-b6ef-416d-b326-ef4bb5613df1",
            "expression": "COALESCE(COUNTROWS(FILTER(Avaliacoes_Maturidade, Avaliacoes_Maturidade[StatusAvaliacao] <> \"Validated\")), 0)",
            "displayFolder": "04 Qualidade",
            "formatString": "0"
          },
          {
            "name": "Total Avaliações",
            "lineageTag": "2917b928-b24a-45e8-9646-2944108e0525",
            "expression": "COALESCE(COUNTROWS(Avaliacoes_Maturidade), 0)",
            "displayFolder": "04 Qualidade",
            "formatString": "0"
          },
          {
            "name": "IDs Duplicados",
            "lineageTag": "80f8a570-9537-489a-a545-9d6d5eeda27b",
            "expression": "COALESCE(COUNTROWS(Avaliacoes_Maturidade) - DISTINCTCOUNT(Avaliacoes_Maturidade[AvaliacaoID]), 0)",
            "displayFolder": "04 Qualidade",
            "formatString": "0"
          },
          {
            "name": "Scores Fora da Faixa",
            "lineageTag": "f544368d-7442-4f45-b2e0-a1af2b54f5b2",
            "expression": "COALESCE(COUNTROWS(FILTER(Score_Por_Pilar, NOT ISBLANK(Score_Por_Pilar[ScorePilar]) && (Score_Por_Pilar[ScorePilar] < 0 || Score_Por_Pilar[ScorePilar] > 3))), 0)",
            "displayFolder": "04 Qualidade",
            "formatString": "0"
          },
          {
            "name": "Avaliações com Pilares Ausentes",
            "lineageTag": "2d750e6c-e2a7-41bd-b54d-dfb390f0dc33",
            "expression": "COALESCE(COUNTROWS(FILTER(VALUES(Avaliacoes_Maturidade[AvaliacaoID]), CALCULATE(COUNTROWS(Score_Por_Pilar)) <> 8)), 0)",
            "displayFolder": "04 Qualidade",
            "formatString": "0"
          },
          {
            "name": "Divergências de Score",
            "lineageTag": "88b29c77-13cc-4629-9005-ba96f2dc72a0",
            "expression": "COALESCE(COUNTROWS(FILTER(Avaliacoes_Maturidade, NOT ISBLANK(Avaliacoes_Maturidade[ScoreGeneral]) && ABS(Avaliacoes_Maturidade[ScoreGeneral] - CALCULATE(AVERAGE(Score_Por_Pilar[ScorePilar]))) > 0.000001)), 0)",
            "displayFolder": "04 Qualidade",
            "formatString": "0"
          },
          {
            "name": "Pilar Menor Score",
            "lineageTag": "c6164f3c-c026-4000-a34e-3c800acba8a8",
            "expression": "VAR IdAtual = [ID Última Avaliação]\nVAR Linhas = FILTER(Score_Por_Pilar, Score_Por_Pilar[AvaliacaoID] = IdAtual)\nRETURN IF(NOT ISBLANK(IdAtual), CONCATENATEX(TOPN(1, Linhas, Score_Por_Pilar[ScorePilar], ASC, Score_Por_Pilar[OrdemPilar], ASC), Score_Por_Pilar[Pilar], \"\"), \"—\")",
            "displayFolder": "01 Visão executiva"
          },
          {
            "name": "Menor Score por Pilar",
            "lineageTag": "10c6e953-ae32-4958-ad55-5244f6c76f92",
            "expression": "VAR IdAtual = [ID Última Avaliação]\nRETURN IF(NOT ISBLANK(IdAtual), MINX(FILTER(Score_Por_Pilar, Score_Por_Pilar[AvaliacaoID] = IdAtual), Score_Por_Pilar[ScorePilar]))",
            "displayFolder": "01 Visão executiva",
            "formatString": "0.00"
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "41090f0b348b4851a1295f1cf94cd638"
          }
        ]
      },
      {
        "name": "Score_Por_Pilar",
        "lineageTag": "92ea8a8a-736f-42ed-8013-83ca9e8d1f5e",
        "columns": [
          {
            "name": "AvaliacaoID",
            "dataType": "int64",
            "sourceColumn": "AvaliacaoID",
            "formatString": "0",
            "lineageTag": "65be2846-1b03-4d0c-b38e-8fec78200e94",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Start time",
            "dataType": "dateTime",
            "sourceColumn": "Start time",
            "formatString": "General Date",
            "lineageTag": "66682293-5c5c-4198-a07b-3c1aa4039ba5",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "relationship": "8beebfc5-982b-419e-9fa1-96e286409e3d",
                "defaultHierarchy": {
                  "table": "LocalDateTable_af044750-2ed3-4c3e-80af-86fd05450e18",
                  "hierarchy": "Hierarquia de datas"
                },
                "isDefault": true
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          },
          {
            "name": "DataAvaliacao",
            "dataType": "dateTime",
            "sourceColumn": "DataAvaliacao",
            "formatString": "yyyy-MM-dd HH:mm",
            "lineageTag": "e852f466-e3f7-42d2-8e79-31917b9f5e42",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "relationship": "5173d7ff-2a90-42a4-85ca-4a7b279733a9",
                "defaultHierarchy": {
                  "table": "LocalDateTable_c53c12ad-3078-4818-8cab-7a73e5f12656",
                  "hierarchy": "Hierarquia de datas"
                },
                "isDefault": true
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "EmailRespondente",
            "dataType": "string",
            "sourceColumn": "EmailRespondente",
            "lineageTag": "d117f75d-2a4c-49a0-8b23-14da74a1c259",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          },
          {
            "name": "Respondente",
            "dataType": "string",
            "sourceColumn": "Respondente",
            "lineageTag": "0955e309-fbc3-43d9-a54c-5054e75b21d5",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          },
          {
            "name": "Cliente",
            "dataType": "string",
            "sourceColumn": "Cliente",
            "lineageTag": "04a7a362-d422-4801-a870-73528d51e65a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "AreaNegocio",
            "dataType": "string",
            "sourceColumn": "AreaNegocio",
            "lineageTag": "7695472a-3dfa-4fb7-80af-7d8ea066ac43",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ScoreGeneral",
            "dataType": "double",
            "sourceColumn": "ScoreGeneral",
            "lineageTag": "8bb27ba9-3f25-4dfa-98c3-f1567d7816d0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "formatString": "0.00"
          },
          {
            "name": "ScoreMaximo",
            "dataType": "int64",
            "sourceColumn": "ScoreMaximo",
            "formatString": "0",
            "lineageTag": "c378ed53-b962-4537-93b2-638969090224",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "DataAvaliacaoDia",
            "dataType": "dateTime",
            "sourceColumn": "DataAvaliacaoDia",
            "formatString": "yyyy-MM-dd",
            "lineageTag": "f9adfc24-cdad-44bc-81b8-86fbea1e4d31",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "relationship": "1df6161f-8114-4529-8082-c46cec8e5b61",
                "defaultHierarchy": {
                  "table": "LocalDateTable_834e9a0d-68f1-46e9-ae2b-f8725c2a40c8",
                  "hierarchy": "Hierarquia de datas"
                },
                "isDefault": true
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ClienteArea",
            "dataType": "string",
            "sourceColumn": "ClienteArea",
            "lineageTag": "1adfb0ba-a324-4f78-bf30-dbbd00c0b32e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "StatusAvaliacao",
            "dataType": "string",
            "sourceColumn": "StatusAvaliacao",
            "lineageTag": "13890d9c-a6ba-4004-a056-0fb30e902bfb",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "CodigoPilar",
            "dataType": "string",
            "sourceColumn": "CodigoPilar",
            "lineageTag": "d7f8ccb8-ad37-4828-8b94-53eeb8a5a3cd",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ScorePilar",
            "dataType": "double",
            "sourceColumn": "ScorePilar",
            "lineageTag": "78ce94f8-3f6b-4115-bdd4-417bde278ec1",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "formatString": "0.00"
          },
          {
            "name": "Pilar",
            "dataType": "string",
            "sourceColumn": "Pilar",
            "lineageTag": "5831e452-1a53-46c0-9c4d-908a09855118",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "sortByColumn": "OrdemPilar"
          },
          {
            "name": "OrdemPilar",
            "dataType": "string",
            "sourceColumn": "OrdemPilar",
            "lineageTag": "b0f0d7b3-1135-4741-bbd9-fa789af0c900",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Score_Por_Pilar",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Fonte = Avaliacoes_Maturidade,",
                "    #\"Colunas Não Dinâmicas\" = Table.Unpivot(Fonte, {\"1_Total\", \"2_Total\", \"3_Total\", \"4_Total\", \"5_Total\", \"6_Total\", \"7_Total\", \"8_Total\"}, \"Atributo\", \"Valor\"),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Colunas Não Dinâmicas\",{{\"Atributo\", \"CodigoPilar\"}, {\"Valor\", \"ScorePilar\"}}),",
                "    #\"Coluna Condicional Adicionada\" = Table.AddColumn(#\"Colunas Renomeadas\", \"Pilar\", each if [CodigoPilar] = \"1_Total\" then \"Policy and Classification\" else if [CodigoPilar] = \"2_Total\" then \"Lineage and Metadata\" else if [CodigoPilar] = \"3_Total\" then \"Data Quality\" else if [CodigoPilar] = \"4_Total\" then \"Master and Reference Data\" else if [CodigoPilar] = \"5_Total\" then \"Security and Access\" else if [CodigoPilar] = \"6_Total\" then \"Data Lifecycle\" else if [CodigoPilar] = \"7_Total\" then \"Collection and Sharing\" else if [CodigoPilar] = \"8_Total\" then \"Audit and Compliance\" else \"Unidentified\"),",
                "    #\"Coluna Condicional Adicionada1\" = Table.AddColumn(#\"Coluna Condicional Adicionada\", \"OrdemPilar\", each if [CodigoPilar] = \"1_Total\" then 1 else if [CodigoPilar] = \"2_Total\" then 2 else if [CodigoPilar] = \"3_Total\" then 3 else if [CodigoPilar] = \"4_Total\" then 4 else if [CodigoPilar] = \"5_Total\" then 5 else if [CodigoPilar] = \"6_Total\" then 6 else if [CodigoPilar] = \"7_Total\" then 7 else if [CodigoPilar] = \"8_Total\" then 8 else 99)",
                "in",
                "    #\"Coluna Condicional Adicionada1\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "LocalDateTable_af044750-2ed3-4c3e-80af-86fd05450e18",
        "isHidden": true,
        "showAsVariationsOnly": true,
        "lineageTag": "ae2d069e-4fb7-46c1-a9a6-9b27cc16d3bb",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "formatString": "General Date",
            "lineageTag": "572bc1f1-f923-44ac-a68a-2852b4c4f6f0",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Ano",
            "dataType": "int64",
            "isHidden": true,
            "expression": "YEAR([Date])",
            "formatString": "0",
            "lineageTag": "a77beb0c-069a-408a-b75b-53e76d0957cf",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "MONTH([Date])",
            "formatString": "0",
            "lineageTag": "3d35129a-7213-40d9-ac1d-67ebd08375ae",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Mês",
            "dataType": "string",
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "0b255e2d-4768-40c1-bc8f-94aad5450e7e",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "lineageTag": "390f82bb-c213-434d-9234-1ee8442794ad",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Trimestre",
            "dataType": "string",
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "967af8be-8bae-4886-a186-60503f0c8980",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Dia",
            "dataType": "int64",
            "isHidden": true,
            "expression": "DAY([Date])",
            "formatString": "0",
            "lineageTag": "3e770f5c-124b-4ed8-bd50-88511fffa104",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "LocalDateTable_af044750-2ed3-4c3e-80af-86fd05450e18",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(Year(MIN('Score_Por_Pilar'[Start time])), 1, 1), Date(Year(MAX('Score_Por_Pilar'[Start time])), 12, 31))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "lineageTag": "5c85c930-5282-46dd-a772-397240b04e1c",
            "levels": [
              {
                "name": "Ano",
                "ordinal": 0,
                "column": "Ano",
                "lineageTag": "7208c911-886c-48d1-8fe3-59509991e8d6"
              },
              {
                "name": "Trimestre",
                "ordinal": 1,
                "column": "Trimestre",
                "lineageTag": "9cd0918d-7ffe-46da-b18f-6689008e6cf9"
              },
              {
                "name": "Mês",
                "ordinal": 2,
                "column": "Mês",
                "lineageTag": "4923259e-9ced-49df-a33f-e37439d957c8"
              },
              {
                "name": "Dia",
                "ordinal": 3,
                "column": "Dia",
                "lineageTag": "cd6c20ab-481b-4962-a404-76f794979d2c"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ]
      },
      {
        "name": "LocalDateTable_c53c12ad-3078-4818-8cab-7a73e5f12656",
        "isHidden": true,
        "showAsVariationsOnly": true,
        "lineageTag": "7f305113-1e93-4c55-8235-438908bf9cd7",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "formatString": "General Date",
            "lineageTag": "f7c7528c-77cc-4569-bc8b-4c51f131771a",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Ano",
            "dataType": "int64",
            "isHidden": true,
            "expression": "YEAR([Date])",
            "formatString": "0",
            "lineageTag": "eb47207e-f05c-466b-81b1-aae414a4c41a",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "MONTH([Date])",
            "formatString": "0",
            "lineageTag": "3a9a0822-6f8e-42ec-86a9-1dc2ccfb0fc5",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Mês",
            "dataType": "string",
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "bc60972e-f2dc-41e3-8a14-36afd8729b22",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "lineageTag": "f7c55def-b4d0-425a-b8a8-4d94d61035f4",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Trimestre",
            "dataType": "string",
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "dfe845a1-c8a2-49f0-ab26-117ab3ea4493",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Dia",
            "dataType": "int64",
            "isHidden": true,
            "expression": "DAY([Date])",
            "formatString": "0",
            "lineageTag": "37577ea2-3459-48a5-ac9f-bc6a662e4d25",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "LocalDateTable_c53c12ad-3078-4818-8cab-7a73e5f12656",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(Year(MIN('Score_Por_Pilar'[DataAvaliacao])), 1, 1), Date(Year(MAX('Score_Por_Pilar'[DataAvaliacao])), 12, 31))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "lineageTag": "2fd8ce27-1102-4a13-9cac-9aa813b2be61",
            "levels": [
              {
                "name": "Ano",
                "ordinal": 0,
                "column": "Ano",
                "lineageTag": "763c8116-391f-4328-bc3f-72e270ddcdc2"
              },
              {
                "name": "Trimestre",
                "ordinal": 1,
                "column": "Trimestre",
                "lineageTag": "b3507cae-99ed-4c6f-b8d8-3cec19160b09"
              },
              {
                "name": "Mês",
                "ordinal": 2,
                "column": "Mês",
                "lineageTag": "140d4a61-5850-47fd-973a-75bce1bf1239"
              },
              {
                "name": "Dia",
                "ordinal": 3,
                "column": "Dia",
                "lineageTag": "6db0dca0-5aa3-417d-b33e-e28e1cf9e5da"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ]
      },
      {
        "name": "LocalDateTable_834e9a0d-68f1-46e9-ae2b-f8725c2a40c8",
        "isHidden": true,
        "showAsVariationsOnly": true,
        "lineageTag": "cc7e1d28-cbab-4a21-977c-52ea26dd2a0d",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "formatString": "General Date",
            "lineageTag": "7253c442-7bc9-4164-8294-91b7f465133e",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Ano",
            "dataType": "int64",
            "isHidden": true,
            "expression": "YEAR([Date])",
            "formatString": "0",
            "lineageTag": "b2506857-1434-4e70-abe2-d203a810af21",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "MONTH([Date])",
            "formatString": "0",
            "lineageTag": "45916371-48d4-4295-be61-84fdd05867a3",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Mês",
            "dataType": "string",
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "b57c7394-6006-4c29-87b7-9a631059cdf0",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "lineageTag": "232350ad-f0a6-4730-8dbf-8b95a671211a",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Trimestre",
            "dataType": "string",
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "8e5f2c3a-7718-4bfc-b1b5-679db57327d5",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Dia",
            "dataType": "int64",
            "isHidden": true,
            "expression": "DAY([Date])",
            "formatString": "0",
            "lineageTag": "b3138cd7-1b37-49ce-9417-33349e2f5afa",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "LocalDateTable_834e9a0d-68f1-46e9-ae2b-f8725c2a40c8",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(Year(MIN('Score_Por_Pilar'[DataAvaliacaoDia])), 1, 1), Date(Year(MAX('Score_Por_Pilar'[DataAvaliacaoDia])), 12, 31))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "lineageTag": "a22cce7c-1b88-49c8-9e22-540be665421e",
            "levels": [
              {
                "name": "Ano",
                "ordinal": 0,
                "column": "Ano",
                "lineageTag": "9d0298dd-f751-4af2-843d-40530092afcb"
              },
              {
                "name": "Trimestre",
                "ordinal": 1,
                "column": "Trimestre",
                "lineageTag": "1ca9ba6b-87f5-4b65-a54e-dc30b7780f91"
              },
              {
                "name": "Mês",
                "ordinal": 2,
                "column": "Mês",
                "lineageTag": "625962cb-29be-477b-98b2-b6d80360610f"
              },
              {
                "name": "Dia",
                "ordinal": 3,
                "column": "Dia",
                "lineageTag": "855a54ab-3432-4496-8565-0c82abba89ca"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "2a1a7c0f-a3a7-4b65-9bc1-5a550b779b2e",
        "fromTable": "Avaliacoes_Maturidade",
        "fromColumn": "Start time",
        "toTable": "LocalDateTable_a80ef2b5-2c9d-4b93-b7fb-2e3338a89f21",
        "toColumn": "Date",
        "joinOnDateBehavior": "datePartOnly"
      },
      {
        "name": "4a6ad4e6-7de2-4062-8e0c-e498ae250ddc",
        "fromTable": "Avaliacoes_Maturidade",
        "fromColumn": "DataAvaliacao",
        "toTable": "LocalDateTable_6dd670b3-9c41-40c2-9037-f42df2a40ccc",
        "toColumn": "Date",
        "joinOnDateBehavior": "datePartOnly"
      },
      {
        "name": "5853bb78-40a9-43b2-9537-30aa47b256ed",
        "fromTable": "Avaliacoes_Maturidade",
        "fromColumn": "DataAvaliacaoDia",
        "toTable": "LocalDateTable_fac499e5-2eb6-445e-9e22-3f649110ac51",
        "toColumn": "Date",
        "joinOnDateBehavior": "datePartOnly"
      },
      {
        "name": "8beebfc5-982b-419e-9fa1-96e286409e3d",
        "fromTable": "Score_Por_Pilar",
        "fromColumn": "Start time",
        "toTable": "LocalDateTable_af044750-2ed3-4c3e-80af-86fd05450e18",
        "toColumn": "Date",
        "joinOnDateBehavior": "datePartOnly"
      },
      {
        "name": "5173d7ff-2a90-42a4-85ca-4a7b279733a9",
        "fromTable": "Score_Por_Pilar",
        "fromColumn": "DataAvaliacao",
        "toTable": "LocalDateTable_c53c12ad-3078-4818-8cab-7a73e5f12656",
        "toColumn": "Date",
        "joinOnDateBehavior": "datePartOnly"
      },
      {
        "name": "1df6161f-8114-4529-8082-c46cec8e5b61",
        "fromTable": "Score_Por_Pilar",
        "fromColumn": "DataAvaliacaoDia",
        "toTable": "LocalDateTable_834e9a0d-68f1-46e9-ae2b-f8725c2a40c8",
        "toColumn": "Date",
        "joinOnDateBehavior": "datePartOnly"
      },
      {
        "name": "AutoDetected_688725e0-0d0a-4269-8c02-b0ffdf429b9e",
        "fromTable": "Score_Por_Pilar",
        "fromColumn": "AvaliacaoID",
        "toTable": "Avaliacoes_Maturidade",
        "toColumn": "AvaliacaoID",
        "crossFilteringBehavior": "oneDirection"
      }
    ],
    "cultures": [
      {
        "name": "en-US"
      }
    ],
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Avaliacoes_Maturidade\",\"Score_Por_Pilar\"]"
      }
    ]
  }
}
